export enum RoleEnum {
	superAdmin = 1,
	admin = 2,
	manager = 3,
	editor = 4,
	creator = 5,
	reviewer = 6,
	player = 7,
	engager = 8,
}

export enum PermissionEnum {
	viewDashboard = 1,

	// profile privacy
	hideEarnings = 2, // don't show earnings on public profile page
	hideProfile = 3, // don't show profile in public search result

	listUsers = 4,
	viewUser = 5,
	createUser = 6,
	updateUser = 7,
	deleteUser = 8,
	forceDeleteUser = 9,
	blockUser = 10,
	unBlockUser = 11,
	updateUserBalance = 12,
	viewTrashedUsers = 13,
	viewTrashedUser = 14,

	listGames = 15,
	viewGame = 16,
	createGame = 17,
	updateGame = 18,
	deleteGame = 19,
	forceDeleteGame = 20,
	blockGame = 21,
	unBlockGame = 22,
	viewTrashedGames = 23,
	viewTrashedGame = 24,

	listGameRooms = 25,
	viewGameRoom = 26,
	createGameRoom = 27,
	updateGameRoom = 28,
	deleteGameRoom = 29,
	forceDeleteGameRoom = 30,
	blockGameRoom = 31,
	unBlockGameRoom = 32,
	createPrivateGameRoom = 33, // don't show the room in available game rooms search page
	viewTrashedGameRooms = 34,
	viewTrashedGameRoom = 35,

	// for both frontend players and backend admin level users
	listTopupRequests = 36,
	viewTopupRequest = 37,
	createTopupRequest = 38,
	updateTopupRequest = 39, // update the transaction screenshot and also for cancel topup request
	deleteTopupRequest = 40,
	forceDeleteTopupRequest = 41,
	reviewTopupRequest = 42,
	viewTrashedTopupRequests = 43,
	viewTrashedTopupRequest = 44,

	// withdrawRequests // for backend admin level user
	listWithdrawRequests = 54,
	viewWithdrawRequest = 55,
	createWithdrawRequest = 56,
	updateWithdrawRequest = 57,
	deleteWithdrawRequest = 58,
	forceDeleteWithdrawRequest = 59,
	reviewWithdrawRequest = 60,
	viewTrashedWithdrawRequests = 61,
	viewTrashedWithdrawRequest = 62,

	// User Role & Permissions
	listRoles = 63,
	viewRole = 64,
	createRole = 65,
	updateRole = 66,
	deleteRole = 67,
	forceDeleteRole = 68,
	reviewRole = 69,
	viewTrashedRoles = 70,
	viewTrashedRole = 71,
	attachRole = 72,
	removeRole = 73,
	addListPermissionsToRole = 74,
	addViewPermissionsToRole = 75,
	addCreatePermissionsToRole = 76,
	addUpdatePermissionsToRole = 77,
	addForceDeletePermissionsToRole = 78,
	addListTrashedPermissionsToRole = 79,
	addViewTrashedPermissionsToRole = 80,
	addReviewPermissionsToRole = 81,
	addOtherPermissionsToRole = 82,

	// Coins Transfer History
	listTransferHistory = 83,
	viewTransferHistoryItem = 84,

	// InApp Notifications
	listInAppNotifications = 85,
	viewInAppNotification = 86,
	createInAppNotification = 87,
	updateInAppNotification = 88,
	deleteInAppNotification = 89,
	forceDeleteInAppNotification = 90,
	viewTrashedInAppNotifications = 91,
	viewTrashedInAppNotification = 92,
	sendInAppNotificationToAllPlayers = 93,
	sendInAppNotificationToAllAdminLevelUsers = 94,
	sendInAppNotificationToSpecificPlayers = 95,
	sendInAppNotificationToSpecificAdminLevelUsers = 96,
	scheduleInAppNotifications = 97,

	listAttachments = 98,
	viewAttachment = 99,
	createAttachment = 100,
	updateAttachment = 101,
	deleteAttachment = 102,
	forceDeleteAttachment = 103,
	viewTrashedAttachments = 104,
	viewTrashedAttachment = 105,

	listAppSettings = 106,
	viewAppSetting = 107,
	createAppSetting = 108,
	updateAppSetting = 109,
	deleteAppSetting = 110,
	forceDeleteAppSetting = 111,
	viewTrashedAppSettings = 112,
	viewTrashedAppSetting = 113,

	listTransactions = 114,
	viewTransaction = 115,
	createTransaction = 116,
	updateTransaction = 117,
	deleteTransaction = 118,
	forceDeleteTransaction = 119,
	viewTrashedTransactions = 120,
	viewTrashedTransaction = 121,
}
