export { checkForDuplicateEnumValues } from './helpers/helpersNeedToLoadBeforeTheyGetUsed/index';

export {
  aesDecrypt,
  decryptData,
  decryptWithSecretKey,
  encryptData,
  encryptWithSecretKey,
} from '../require-package/crypto-js';
export {
  convertToDateTimestampToStoreInDB,
  getDateFromFrbTimestamp,
  getRemainingTimeForCountDown,
} from '../require-package/dayjs';
export { apiHeaderKeys } from './constants/apiConstants';
export { frbCollectionQueryDefaults } from './constants/firebaseConstants';
export {
  allowedImageTypes,
  apiConstants,
  dateFormat,
  dayjs,
  defaultValue,
  fieldsValidation,
  svgIconTypes,
  timeUnitType,
  urlParams,
  urlTarget,
} from './constants/generic';
export { permissionsData } from './constants/permissions';
export { rolePermissionsMap } from './constants/rolePermissionsConstants';
export { reportCustomError } from './helpers/errorHandler';
export {
  addUrlProtocolHandler,
  buildFilterObject,
  calcCrow,
  checkEqualityOfTwoArray,
  checkIfKeyExists,
  checkVariableType,
  containQueryParams,
  containSpecialCharacters,
  convertToTitleCase,
  convertToTitleCaseV1,
  createRegexMatch,
  dbItemIsBlocked,
  detectDeviceAndViewMode,
  dumpValueNoLogNothing,
  emptyVoidReturnFunction,
  emptyVoidReturnFunctionPromise,
  escapeRegex,
  flattenArray,
  formatStripeAmount,
  formatUSD,
  generateSlug,
  generateUniqueCode,
  generateUUID,
  getActiveFilters,
  getDBTimeColumnValue,
  getImageAspectRatio,
  getImageBase64Url,
  getImageDimensions,
  getObjectKey,
  getPaginationParams,
  getTextOnly,
  getTimeInUnit,
  getZUniqueKey,
  hasLeadingOrTrailingSlash,
  imageTypeAllowed,
  imageUrlToBase64,
  isArray,
  isEqual,
  isFileTypeAllowed,
  isFileTypeValid,
  isFunction,
  isNotNullOrUndefined,
  isNullOrUndefined,
  isObject,
  isSoftDeleted,
  isStringVariable,
  isValidEmail,
  isValidUrl,
  isValidVanityUrl,
  isZNonEmptyString,
  isZNonEmptyStrings,
  isZValidNumber,
  isZValidNumbers,
  normalizeEnumValue,
  removeLeadingTrailingBackslash,
  replaceUrlDynamicParts,
  toRad,
  truncateString,
  validateFileBeforeUpload,
  zConvertToBoolean,
  zJsonParse,
  zStringify,
  ZTotalPages,
} from './helpers/generic';
export {
  getPermissions,
  getUserRoleEnumValueFromString,
  hasPermission,
  mapPermissionsToStrings,
  validateExcludedPermissions,
  validateRequiredPermissions,
  validateUserPermissions,
} from './helpers/rolePermissionsHelpers';
export {
  validateEmail,
  validatePhoneNumber,
  validateURL,
} from './helpers/validators';
export { ztkMessages } from './messages';
